### ISSUE TITLE
[FEAT]Tools tracking and Character skill tracking

### ISSUE THREAD

**Issue by Teraphas** [Musimaniac/IdleonCompanion#111] opened 2021-05-25 20:36 UTC
**Which categories does your suggestion apply to?**
- [ ] UI changes
- [ ] Tracking
- [ ] Calculators
- [ ] Other tools/misc

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add equipped Tools to the character sheets. allow the tool to gain some sort of tag or colored background to indicate when the skill level on the character would allow for a stronger tool to be equipped

for example Character has a copper axe equipped. once the skill level reaches or exceeds 18 the copper axe would gain the flag letting the user easily see that they should be looking into giving the character the next strongest tool
**What data is needed for the suggestion?**
_links to Wiki, external tools, etc. are helpful!_

**Additional context**

**Comment by adapap** [comment] 2021-05-31 22:36
Duplicate of #50

**Closed by adapap** 2021-05-31 22:36 UTC
