### ISSUE TITLE
Character cards overflow on characters page

### ISSUE THREAD

**Issue by adapap** [Musimaniac/IdleonCompanion#31] opened 2021-04-06 00:42 UTC
On mobile character cards get cut off

![image](https://user-images.githubusercontent.com/19696846/113643092-7259c280-964f-11eb-8225-97aede2d5afd.png)

label:bug

**Comment by Musimaniac** [comment] 2021-04-06 04:54
possible duplicate of #21

**Closed** 2021-04-06 17:43 UTC
Labels: bug, duplicate
